Resources:
  SampleLambdaFunction:
    Properties:
      CodeUri: .
      FunctionName: lambda-move-object
      Handler: lambda_function.lambda_handler
      #Role: !ImportValue 'cfn-cicd-leo-role2'
      Runtime: python3.8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31